### ISSUE TITLE
[account] 생성

### ISSUE THREAD

**Issue by Silver-Deer** [jobda-keychain/keychain#1]
![image](https://user-images.githubusercontent.com/62982576/148345946-d8a389e7-f180-4ced-a763-cfdaf1f38e5f.png)

### 요청 사항
- 아이디(로그인할 때 사용할 아이디)
- 비밀번호(로그인할 때 사용할 비밀번호)
- 환경(dv, st, pr... 현재 이 유저가 어느 상태에 있는지 보여준다.)
    - 유저가 직접 추가할 수 있다. dv-1, dv-2...
- 서비스(jobda, jobda-cms  유저인지 관리자인지)
- 상세설명(100자)

**Comment by shfksekdrms2** [comment]
https://github.com/shfksekdrms2/inflearn/issues
@Silver-Deer @m04j00 
이슈는 기획 레벨에 맞춰서 
main > user > 생성, [main][user] 생성

이런씩처럼 한번에 보기 편하게 해주시면 좋을거같아요~!
정형화 되어 있으면 좋을거같아요
