### ISSUE TITLE
[검증] 환경 관리 메인

### ISSUE THREAD

**Issue by Silver-Deer** [jobda-keychain/keychain#189]
- [x]  탭 이동이 잘 되는지
- [x]  클라이언트 도메인을 클릭했을 때 해당 도메인으로 이동이 되는지

**Comment by syxxn** [comment]
요청
+ 클라이언트 도메인 누르면 새 탭으로 이동하기
+ 도메인은 정규표현식으로 막기
+ 요만 잘리는거 정리해주세요
