### ISSUE TITLE
예외 처리

### ISSUE THREAD

**Issue by m04j00** [jobda-keychain/keychain#23]

**Comment by syxxn** [comment]
https://github.com/EntryDSM/Rolls-Royce/tree/main/src/main/java/kr/hs/entrydsm/rollsroyce/global/error

**Comment by syxxn** [comment]
https://github.com/EntryDSM/Rolls-Royce/tree/main/src/main/java/kr/hs/entrydsm/rollsroyce/global/exception

**Comment by syxxn** [comment]
```
@ResponseStatus(value = HttpStatus.NOT_FOUND, reason = "UserNotFound")
public class UserNotFoundException extends RuntimeException {
}
```

**Comment by syxxn** [comment]
- [ ] Validation 핸들링
- [ ] UserNotFoundException
- [ ] EnvironmentNotFoundException
