### ISSUE TITLE
2차 스프린트 기능 확정

### ISSUE THREAD

**Issue by shfksekdrms2** [jobda-keychain/keychain#35]
- 2차 스프린트에 포함되는 이슈 확정
- 2차에 포함되지 않는 이슈는 3차 마일스톤으로 이동
- 기능 확정 후 각 이슈에 대한 시간 산정
- 역할 분담

**Comment by shfksekdrms2** [comment]
@syxxn 기능확정되고 정리된 내용있을까요?

**Comment by syxxn** [comment]
![image](https://user-images.githubusercontent.com/64132926/148728593-07c7c1cb-81f8-4572-8aaa-7c956d0aa593.png)
노션 일정 페이지에 각 기능별 일정을 기록해두었습니다. 이번주에 해야할 일들은 이슈로 리스트업 해두었구요, 각 기능 개발과 단위 테스트를 함께 하기로 결정해서 시간을 넉넉히 잡았습니다. 기획서는 수정해서 올려뒀고, 형규님께 피드백받은 후 개발 진행중입니다!

**Comment by syxxn** [comment]
일정 피드백 받았는데, 태스크 별로 일정을 잡으면 좋을 것 같다고 하셔서 내일 일정 다시 조율하면서 test 라이브러리 공부하기로 했습니다
